import BaseSeeder from '@ioc:Adonis/Lucid/Seeder';
import Lesson from 'App/Models/Lesson';

export default class LessonSeeder extends BaseSeeder {
  public static developmentOnly = true;

  public async run() {
    await Lesson.updateOrCreateMany(
      ['day', 'period', 'subjectId', 'timetableId'],
      [
        { day: 1, period: 1, subjectId: 1, timetableId: 1 },
        { day: 1, period: 2, subjectId: 2, timetableId: 1 },
        { day: 1, period: 3, subjectId: 6, timetableId: 1 },
        { day: 1, period: 5, subjectId: 9, timetableId: 1 },
        { day: 1, period: 6, subjectId: 12, timetableId: 1 },
        { day: 1, period: 7, subjectId: 12, timetableId: 1 },
        { day: 1, period: 8, subjectId: 4, timetableId: 1 },
        { day: 2, period: 1, subjectId: 1, timetableId: 1 },
        { day: 2, period: 2, subjectId: 10, timetableId: 1 },
        { day: 2, period: 3, subjectId: 10, timetableId: 1 },
        { day: 2, period: 5, subjectId: 13, timetableId: 1 },
        { day: 2, period: 6, subjectId: 3, timetableId: 1 },
        { day: 2, period: 7, subjectId: 7, timetableId: 1 },
        { day: 2, period: 7, subjectId: 14, timetableId: 1 },
        { day: 2, period: 8, subjectId: 4, timetableId: 1 },
        { day: 3, period: 1, subjectId: 7, timetableId: 1 },
        { day: 3, period: 1, subjectId: 14, timetableId: 1 },
        { day: 3, period: 2, subjectId: 4, timetableId: 1 },
        { day: 3, period: 3, subjectId: 5, timetableId: 1 },
        { day: 3, period: 5, subjectId: 1, timetableId: 1 },
        { day: 3, period: 6, subjectId: 3, timetableId: 1 },
        { day: 3, period: 7, subjectId: 13, timetableId: 1 },
        { day: 3, period: 8, subjectId: 13, timetableId: 1 },
        { day: 4, period: 0, subjectId: 10, timetableId: 1 },
        { day: 4, period: 1, subjectId: 10, timetableId: 1 },
        { day: 4, period: 2, subjectId: 8, timetableId: 1 },
        { day: 4, period: 3, subjectId: 8, timetableId: 1 },
        { day: 4, period: 5, subjectId: 11, timetableId: 1 },
        { day: 4, period: 6, subjectId: 11, timetableId: 1 },
        { day: 5, period: 0, subjectId: 3, timetableId: 1 },
        { day: 5, period: 1, subjectId: 3, timetableId: 1 },
        { day: 5, period: 2, subjectId: 4, timetableId: 1 },
        { day: 5, period: 3, subjectId: 9, timetableId: 1 },
        { day: 5, period: 5, subjectId: 14, timetableId: 1 },
        { day: 5, period: 5, subjectId: 7, timetableId: 1 },
        { day: 5, period: 6, subjectId: 1, timetableId: 1 },

        { day: 1, period: 1, subjectId: 6, timetableId: 2 },
        { day: 1, period: 2, subjectId: 4, timetableId: 2 },
        { day: 1, period: 3, subjectId: 1, timetableId: 2 },
        { day: 1, period: 5, subjectId: 3, timetableId: 2 },
        { day: 1, period: 6, subjectId: 18, timetableId: 2 },
        { day: 1, period: 7, subjectId: 18, timetableId: 2 },
        { day: 1, period: 8, subjectId: 11, timetableId: 2 },
        { day: 2, period: 1, subjectId: 3, timetableId: 2 },
        { day: 2, period: 2, subjectId: 14, timetableId: 2 },
        { day: 2, period: 2, subjectId: 7, timetableId: 2 },
        { day: 2, period: 3, subjectId: 1, timetableId: 2 },
        { day: 2, period: 5, subjectId: 4, timetableId: 2 },
        { day: 2, period: 6, subjectId: 15, timetableId: 2 },
        { day: 2, period: 7, subjectId: 17, timetableId: 2 },
        { day: 3, period: 1, subjectId: 11, timetableId: 2 },
        { day: 3, period: 2, subjectId: 3, timetableId: 2 },
        { day: 3, period: 3, subjectId: 1, timetableId: 2 },
        { day: 3, period: 5, subjectId: 4, timetableId: 2 },
        { day: 3, period: 6, subjectId: 7, timetableId: 2 },
        { day: 3, period: 6, subjectId: 14, timetableId: 2 },
        { day: 3, period: 7, subjectId: 6, timetableId: 2 },
        { day: 3, period: 8, subjectId: 17, timetableId: 2 },
        { day: 4, period: 0, subjectId: 8, timetableId: 2 },
        { day: 4, period: 1, subjectId: 8, timetableId: 2 },
        { day: 4, period: 2, subjectId: 4, timetableId: 2 },
        { day: 4, period: 3, subjectId: 3, timetableId: 2 },
        { day: 4, period: 5, subjectId: 16, timetableId: 2 },
        { day: 4, period: 6, subjectId: 16, timetableId: 2 },
        { day: 4, period: 7, subjectId: 1, timetableId: 2 },
        { day: 5, period: 0, subjectId: 15, timetableId: 2 },
        { day: 5, period: 1, subjectId: 14, timetableId: 2 },
        { day: 5, period: 1, subjectId: 7, timetableId: 2 },
        { day: 5, period: 2, subjectId: 10, timetableId: 2 },
        { day: 5, period: 3, subjectId: 10, timetableId: 2 },
        { day: 5, period: 5, subjectId: 13, timetableId: 2 },
        { day: 5, period: 6, subjectId: 13, timetableId: 2 },

        { day: 1, period: 1, subjectId: 25, timetableId: 3 },
        { day: 1, period: 2, subjectId: 26, timetableId: 3 },
        { day: 1, period: 3, subjectId: 19, timetableId: 3 },
        { day: 1, period: 3, subjectId: 20, timetableId: 3 },
        { day: 1, period: 4, subjectId: 30, timetableId: 3 },
        { day: 1, period: 5, subjectId: 20, timetableId: 3 },
        { day: 1, period: 5, subjectId: 19, timetableId: 3 },
        { day: 1, period: 6, subjectId: 21, timetableId: 3 },
        { day: 2, period: 1, subjectId: 19, timetableId: 3 },
        { day: 2, period: 2, subjectId: 32, timetableId: 3 },
        { day: 2, period: 3, subjectId: 22, timetableId: 3 },
        { day: 2, period: 3, subjectId: 23, timetableId: 3 },
        { day: 2, period: 4, subjectId: 20, timetableId: 3 },
        { day: 2, period: 5, subjectId: 28, timetableId: 3 },
        { day: 2, period: 6, subjectId: 24, timetableId: 3 },
        { day: 3, period: 1, subjectId: 19, timetableId: 3 },
        { day: 3, period: 1, subjectId: 20, timetableId: 3 },
        { day: 3, period: 2, subjectId: 25, timetableId: 3 },
        { day: 3, period: 3, subjectId: 20, timetableId: 3 },
        { day: 3, period: 3, subjectId: 19, timetableId: 3 },
        { day: 3, period: 4, subjectId: 27, timetableId: 3 },
        { day: 3, period: 5, subjectId: 26, timetableId: 3 },
        { day: 3, period: 6, subjectId: 30, timetableId: 3 },
        { day: 3, period: 8, subjectId: 33, timetableId: 3 },
        { day: 4, period: 1, subjectId: 19, timetableId: 3 },
        { day: 4, period: 2, subjectId: 20, timetableId: 3 },
        { day: 4, period: 3, subjectId: 22, timetableId: 3 },
        { day: 4, period: 3, subjectId: 23, timetableId: 3 },
        { day: 4, period: 4, subjectId: 21, timetableId: 3 },
        { day: 4, period: 5, subjectId: 24, timetableId: 3 },
        { day: 4, period: 6, subjectId: 29, timetableId: 3 },
        { day: 5, period: 1, subjectId: 21, timetableId: 3 },
        { day: 5, period: 2, subjectId: 27, timetableId: 3 },
        { day: 5, period: 3, subjectId: 19, timetableId: 3 },
        { day: 5, period: 4, subjectId: 31, timetableId: 3 },
        { day: 5, period: 5, subjectId: 20, timetableId: 3 },
        { day: 5, period: 6, subjectId: 28, timetableId: 3 },
      ]
    );
  }
}
